### ISSUE TITLE
Rcpp error: no matching function for call to 'R_useDynamicSymbols', shown in macOS 10.14 + R 3.5.1

### ISSUE THREAD

**Issue by xiangzhu** [stephenslab/ldshrink#21]
I came across the following error in my mac laptop:

```r
> devtools::load_all(".")

[omitted]

RcppExports.cpp:242:5: error: no matching function for call to 'R_useDynamicSymbols'
    R_useDynamicSymbols(dll, FALSE);
    ^~~~~~~~~~~~~~~~~~~
/Library/Frameworks/R.framework/Resources/include/R_ext/Rdynload.h:84:10: note: candidate function not viable: no known conversion from 'int' to 'Rboolean' for 2nd argument
Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
         ^
4 warnings and 1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘ldshrink’
* removing ‘/private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmpjSVD5F/devtools_install_60b7e017afc/ldshrink’
Error: Command failed (1)
```

Here is my laptop info:

```bash
# xiangzhu @ stanford in ~ [22:27:51]
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14 (18A391)
      Kernel Version: Darwin 18.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: STA-C02V26FCHTD5
      User Name: Xiang Zhu (xiangzhu)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 days 22:05
```

Here is my R session info:

```R
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-10-04                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------
 package      * version   date       source        
 base         * 3.5.1     2018-07-05 local         
 BH             1.66.0-1  2018-02-13 CRAN (R 3.5.0)
 commonmark     1.6       2018-09-30 CRAN (R 3.5.0)
 compiler       3.5.1     2018-07-05 local         
 datasets     * 3.5.1     2018-07-05 local         
 devtools       1.13.6    2018-06-27 CRAN (R 3.5.0)
 digest         0.6.17    2018-09-12 CRAN (R 3.5.1)
 graphics     * 3.5.1     2018-07-05 local         
 grDevices    * 3.5.1     2018-07-05 local         
 grid           3.5.1     2018-07-05 local         
 lattice        0.20-35   2017-03-25 CRAN (R 3.5.1)
 magrittr       1.5       2014-11-22 CRAN (R 3.5.0)
 Matrix         1.2-14    2018-04-13 CRAN (R 3.5.1)
 memoise        1.1.0     2017-04-21 CRAN (R 3.5.0)
 methods      * 3.5.1     2018-07-05 local         
 R6             2.3.0     2018-10-04 CRAN (R 3.5.1)
 Rcpp           0.12.19   2018-10-01 CRAN (R 3.5.0)
 RcppEigen      0.3.3.4.0 2018-02-07 CRAN (R 3.5.0)
 RcppParallel   4.4.1     2018-07-19 CRAN (R 3.5.0)
 RcppProgress   0.4.1     2018-05-11 CRAN (R 3.5.0)
 rlang          0.2.2     2018-08-16 CRAN (R 3.5.0)
 roxygen2       6.1.0     2018-07-27 CRAN (R 3.5.0)
 stats        * 3.5.1     2018-07-05 local         
 stringi        1.2.4     2018-07-20 CRAN (R 3.5.0)
 stringr        1.3.1     2018-05-10 CRAN (R 3.5.0)
 testthat       2.0.0     2017-12-13 CRAN (R 3.5.0)
 tools          3.5.1     2018-07-05 local         
 utils        * 3.5.1     2018-07-05 local         
 withr          2.1.2     2018-03-15 CRAN (R 3.5.0)
 xml2           1.2.0     2018-01-24 CRAN (R 3.5.0)
 yaml           2.2.0     2018-07-25 CRAN (R 3.5.0)
```

**Comment by xiangzhu** [comment]
@CreRecombinase  i tried it again on my Linux desktop; the Rcpp error disappeared but the following error came out:

```r
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o ldshrink.so LD.o LD_p.o RcppExports.o SNPcoord.o -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
installing to /tmp/Rtmp5x73rF/devtools_install_5d726e9d469/ldshrink/libs
* DONE (ldshrink)
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
> library(ldshrink)
Error in library(ldshrink) : there is no package called ‘ldshrink’
```

below is my linux desktop info:

```bash
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

below is the R session info:

```r
> devtools::session_info()

setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-10-04

package      * version   date       source        
 assertthat     0.2.0     2017-04-11 CRAN (R 3.5.1)
 backports      1.1.2     2017-12-13 CRAN (R 3.5.1)
 base         * 3.5.1     2018-07-03 local         
 BBmisc         1.11      2017-03-10 CRAN (R 3.5.1)
 BH             1.66.0-1  2018-02-13 CRAN (R 3.5.1)
 bindr          0.1.1     2018-03-13 CRAN (R 3.5.1)
 bindrcpp       0.2.2     2018-03-29 CRAN (R 3.5.1)
 checkmate      1.8.5     2017-10-24 CRAN (R 3.5.1)
 commonmark     1.6       2018-09-30 CRAN (R 3.5.1)
 compiler       3.5.1     2018-07-03 local         
 crayon         1.3.4     2017-09-16 CRAN (R 3.5.1)
 datasets     * 3.5.1     2018-07-03 local         
 devtools       1.13.6    2018-06-27 CRAN (R 3.5.1)
 digest         0.6.17    2018-09-12 CRAN (R 3.5.1)
 dplyr          0.7.6     2018-06-29 CRAN (R 3.5.1)
 glue           1.3.0     2018-07-17 CRAN (R 3.5.1)
 graphics     * 3.5.1     2018-07-03 local         
 grDevices    * 3.5.1     2018-07-03 local         
 grid           3.5.1     2018-07-03 local         
 hms            0.4.2     2018-03-10 CRAN (R 3.5.1)
 lattice        0.20-35   2017-03-25 CRAN (R 3.5.1)
 ldshrink       1.0       <NA>       local         
 magrittr       1.5       2014-11-22 CRAN (R 3.5.1)
 Matrix         1.2-14    2018-04-09 CRAN (R 3.5.1)
 memoise        1.1.0     2017-04-21 CRAN (R 3.5.1)
 methods      * 3.5.1     2018-07-03 local         
 pillar         1.3.0     2018-07-14 CRAN (R 3.5.1)
 pkgconfig      2.0.2     2018-08-16 CRAN (R 3.5.1)
 prettyunits    1.0.2     2015-07-13 CRAN (R 3.5.1)
 progress       1.2.0     2018-06-14 CRAN (R 3.5.1)
 purrr          0.2.5     2018-05-29 CRAN (R 3.5.1)
 R6             2.3.0     2018-10-04 CRAN (R 3.5.1)
 Rcpp           0.12.19   2018-10-01 CRAN (R 3.5.1)
 RcppEigen      0.3.3.4.0 2018-02-07 CRAN (R 3.5.1)
 RcppParallel   4.4.1     2018-07-19 CRAN (R 3.5.1)
 RcppProgress   0.4.1     2018-05-11 CRAN (R 3.5.1)
 rlang          0.2.2     2018-08-16 CRAN (R 3.5.1)
 roxygen2       6.1.0     2018-07-27 CRAN (R 3.5.1)
 rstudioapi     0.8       2018-10-02 CRAN (R 3.5.1)
 stats        * 3.5.1     2018-07-03 local         
 stringi        1.2.4     2018-07-20 CRAN (R 3.5.1)
 stringr        1.3.1     2018-05-10 CRAN (R 3.5.1)
 testthat       2.0.0     2017-12-13 CRAN (R 3.5.1)
 tibble         1.4.2     2018-01-22 CRAN (R 3.5.1)
 tidyselect     0.2.4     2018-02-26 CRAN (R 3.5.1)
 tools          3.5.1     2018-07-03 local         
 utils        * 3.5.1     2018-07-03 local         
 withr          2.1.2     2018-03-15 CRAN (R 3.5.1)
 xml2           1.2.0     2018-01-24 CRAN (R 3.5.1)
```

**Comment by xiangzhu** [comment]
@CreRecombinase  i think this issue should be re-stated as: if i type `devtools::load_all(".")` in R, i will get some sort of errors, depending on which OS i am using ...

perhaps the linux error is easier to fix? this is also good for long term, since you are also using linux

**Comment by CreRecombinase** [comment]
I believe the issue is fixed in the latest version.  It stemmed from: 
1) In the `NAMESPACE` file `useDynLib(LDshrink, .registration=TRUE)` had to be changed to `useDynLib(ldshrink, .registration=TRUE)`
2) Every time `c++` functions (or their signatures) are added/removed or changed it is important to run `Rcpp::compileAttributes()` from inside the package and to do a clean rebuild (this can be done in Rstudio under the "Build" tab by clicking "More->Clean and Rebuild" 

I'll leave this open for now while we work out the mac issue

**Comment by xiangzhu** [comment]
@pcarbo  I guess you tested it on Mac, right? I will continue working on this package in my Linux machine, since Nick is also working in Linux.

In addition, I was getting some `clang error` before this `Rcpp` error, and I found your notes here super helpful in removing the `clang error`: https://github.com/stephenslab/lab-resource/blob/master/utilities/wiki/R-3.4-mac.md

Thanks for the great note!

**Comment by xiangzhu** [comment]
@CreRecombinase  To confirm, when you say "the issue is fixed in the latest version", it means that it is resolved in Linux, right? If so I can test it around 5 pm PT today.

If the current package works in Linux for development, I will switch to Linux so that we have similar working environment.

**Comment by pcarbo** [comment]
I can confirm that it works in a Linux OS, for `ldshrink` 1.0-1. Here is my sessionInfo:

```R
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /software/openblas-0.2.19-el7-x86_64/lib/libopenblas_haswellp-r0.2.19.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ldshrink_1.0-1  devtools_1.13.6

loaded via a namespace (and not attached):
 [1] compiler_3.5.1      RcppEigen_0.3.3.4.0 magrittr_1.5
 [4] Matrix_1.2-14       tools_3.5.1         withr_2.1.2
 [7] Rcpp_0.12.18        memoise_1.1.0       grid_3.5.1
[10] git2r_0.23.0        digest_0.6.15       RcppParallel_4.4.1
[13] lattice_0.20-35
```

**Comment by pcarbo** [comment]
I can confirm now that it also works on Mac, for `ldshrink` 1.0-1. Here is my sessionInfo:

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ldshrink_1.0-1

loaded via a namespace (and not attached):
 [1] compiler_3.4.3      RcppEigen_0.3.3.4.0 magrittr_1.5
 [4] Matrix_1.2-12       tools_3.4.3         withr_2.1.2
 [7] Rcpp_0.12.19        memoise_1.1.0       grid_3.4.3
[10] git2r_0.23.0        digest_0.6.17       RcppParallel_4.4.1
[13] devtools_1.13.6     lattice_0.20-35
```

**Comment by pcarbo** [comment]
@xiangzhou @CreRecombinase You are welcome to close this issue.

**Comment by xiangzhu** [comment]
@CreRecombinase Thanks for the fix!

The command `devtools::load_all(".")` is running without error in my Linux machine after this fix.

However I am still getting the same error in macOS 10.14 (18A391) + R 3.5.1:

```r
RcppExports.cpp:217:5: error: no matching function for call to 'R_useDynamicSymbols'
    R_useDynamicSymbols(dll, FALSE);
    ^~~~~~~~~~~~~~~~~~~
/Library/Frameworks/R.framework/Resources/include/R_ext/Rdynload.h:84:10: note: candidate function not viable: no known conversion from 'int' to 'Rboolean' for 2nd argument
Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
         ^
4 warnings and 1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘ldshrink’
* removing ‘/private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmpFrltHw/devtools_install_731b254cabfa/ldshrink’
Error: Command failed (1)
```

I googled this again, and I speculate this may be a Rcpp issue. For now I will work on Linux only, the same environment as yours.

**Comment by pcarbo** [comment]
@xiangzhu `load_all` actually does something different than installing the package; in particular, it will also update the Rcpp code when needed. I also get the same error when running `load_all`. If you run, for example, `devtools::install_local()`, instead, it should work (at least it does on my Mac). On the other hand, you will likely get an error when you run `devtools::document()`, which will update the Rcpp code.

I'm not sure why updating the Rcpp code works on Linux, and not on Mac, but it does suggest a fragility with the C++ code that needs to be addressed at some point.

Also, when reporting errors, it is helpful to report the commit id of the repository you are using so we can more easily reproduce the error.

**Comment by pcarbo** [comment]
@xiangzhu Can you try following my suggestions on your Mac to see if you observe the same behaviour?
